# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/model.proto',
  package='protos',
  syntax='proto3',
  serialized_pb=_b('\n\x12protos/model.proto\x12\x06protos\">\n\x13\x43lassificationModel\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x13\n\x0bnum_classes\x18\x02 \x01(\rb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CLASSIFICATIONMODEL = _descriptor.Descriptor(
  name='ClassificationModel',
  full_name='protos.ClassificationModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_name', full_name='protos.ClassificationModel.model_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_classes', full_name='protos.ClassificationModel.num_classes', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['ClassificationModel'] = _CLASSIFICATIONMODEL

ClassificationModel = _reflection.GeneratedProtocolMessageType('ClassificationModel', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFICATIONMODEL,
  __module__ = 'protos.model_pb2'
  # @@protoc_insertion_point(class_scope:protos.ClassificationModel)
  ))
_sym_db.RegisterMessage(ClassificationModel)


# @@protoc_insertion_point(module_scope)
