# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/pipeline.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import train_pb2 as protos_dot_train__pb2
from protos import model_pb2 as protos_dot_model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/pipeline.proto',
  package='protos',
  syntax='proto3',
  serialized_pb=_b('\n\x15protos/pipeline.proto\x12\x06protos\x1a\x12protos/train.proto\x1a\x12protos/model.proto\"z\n\x0ePipelineConfig\x12\x11\n\tdata_root\x18\x01 \x01(\t\x12*\n\x05model\x18\x02 \x01(\x0b\x32\x1b.protos.ClassificationModel\x12)\n\x0ctrain_config\x18\x03 \x01(\x0b\x32\x13.protos.TrainConfigb\x06proto3')
  ,
  dependencies=[protos_dot_train__pb2.DESCRIPTOR,protos_dot_model__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PIPELINECONFIG = _descriptor.Descriptor(
  name='PipelineConfig',
  full_name='protos.PipelineConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_root', full_name='protos.PipelineConfig.data_root', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='protos.PipelineConfig.model', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_config', full_name='protos.PipelineConfig.train_config', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=195,
)

_PIPELINECONFIG.fields_by_name['model'].message_type = protos_dot_model__pb2._CLASSIFICATIONMODEL
_PIPELINECONFIG.fields_by_name['train_config'].message_type = protos_dot_train__pb2._TRAINCONFIG
DESCRIPTOR.message_types_by_name['PipelineConfig'] = _PIPELINECONFIG

PipelineConfig = _reflection.GeneratedProtocolMessageType('PipelineConfig', (_message.Message,), dict(
  DESCRIPTOR = _PIPELINECONFIG,
  __module__ = 'protos.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:protos.PipelineConfig)
  ))
_sym_db.RegisterMessage(PipelineConfig)


# @@protoc_insertion_point(module_scope)
